version: "3.8"
services:
  selenium:
    image: seleniarm/standalone-chromium:latest
    restart: unless-stopped
    shm_size: 2gb
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444"]
      interval: 10s
      timeout: 5s
      retries: 5

  worldcat-reconciliation-service:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      selenium:
        condition: service_healthy
    environment:
      - REMOTE_WEBDRIVER_ADDRESS=http://selenium:4444
      - RECONCILIATION_SERVICE_DOMAIN=${RECONCILIATION_SERVICE_DOMAIN?RECONCILIATION_SERVICE_DOMAIN not set}
    ports:
      - "80:80"
